# Create two SSE-S3 encrypted buckets.
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  bucket1:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "wh-src"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  bucket2:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "wh-dest"

  S3PublicPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: bucket1
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::wh-src/*
