# Duplicate files from source to destination
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  bucket1:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "wh-src"
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: !GetAtt ReplicationRole.Arn
        Rules:
          - Id: ReplicationRule
            Destination:
              Bucket: !GetAtt bucket2.Arn
              StorageClass: STANDARD
            Prefix: ""
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  bucket2:
    Type: "AWS::S3::Bucket"
    UpdateReplacePolicy: "Retain"
    DeletionPolicy: "Retain"
    Properties:
      BucketName: "wh-dest"
      VersioningConfiguration:
        Status: Enabled

  S3PublicPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: bucket1
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::wh-src/*

  ReplicationRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ReplicationRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: ReplicationPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetReplicationConfiguration
                  - s3:ListBucket
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:GetObjectVersionTorrent
                  - s3:GetObjectVersionWebsite
                Resource:
                  - "arn:aws:s3:::wh-src"
                  - "arn:aws:s3:::wh-src/*"
                  - "arn:aws:s3:::wh-dest"
                  - "arn:aws:s3:::wh-dest/*"

  # ReplicationConfiguration:
  #   Type: "AWS::S3::Bucket"
  #   Properties:
  #     BucketName: wh-src
  #     ReplicationConfiguration:
  #       Role: !GetAtt ReplicationRole.Arn
  #       Rules:
  #         - Id: ReplicationRule
  #           Destination:
  #             Bucket: !Ref bucket
  #             StorageClass: STANDARD
  #           Prefix: ""
  #           Status: Enabled
